# Generated by Django 4.2.10 on 2024-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("rating", models.FloatField()),
                ("average_rating", models.FloatField()),
            ],
        ),
    ]
